### ISSUE TITLE
Forward logs to a SaaS log collector service

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-api#108]
Configure all our services running on Fly to forward the logs to a log collector service. 

This should help us troubleshoot problems like https://github.com/filecoin-station/spark/issues/35

```[tasklist]
### Tasks
- [x] Setup an account with the chosen SaaS provider, give access to all team members
- [x] Setup log forwarding for spark-api
- [x] Setup log forwarding for spark-publish
- [x] Setup log forwarding for spark-evaluate
```

**Comment by bajtos** [comment]
Fly.io docs on log forwarding: https://fly.io/docs/going-to-production/monitoring/exporting-logs/

**Comment by bajtos** [comment]
In https://filecoinproject.slack.com/archives/C03PQG6UT2B/p1697436851193249, we agreed to use https://www.papertrail.com

In https://filecoinproject.slack.com/archives/C05V4TYD49W/p1697700210198619, we discussed exploring Grafana Cloud as well since we already use Grafana for metrics & visualisations.

**Comment by juliangruber** [comment]
I'm not seeing any logs in https://my.eu-01.cloud.solarwinds.com/195053688648477696/logs yet btw, and don't have access to papertrailapp.com

**Comment by juliangruber** [comment]
Shall I sign up there as well?

**Comment by juliangruber** [comment]
(I have only used PT from the papertrailapp.com before, don't know about the solarwinds stuff)

**Comment by bajtos** [comment]
> I'm not seeing any logs in https://my.eu-01.cloud.solarwinds.com/195053688648477696/logs yet btw, and don't have access to papertrailapp.com
> Shall I sign up there as well?

Sorry, I was confused and accidentally created accounts in the wrong service.

Here is the correct Dashboard URL where you will see logs.
https://papertrailapp.com/dashboard
