### ISSUE TITLE
Meridian: Measure commit phase

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/spark-api#42]
```[tasklist]
### Tasks
- [x] Aggregate measurements
- [x] Expose via IPFS
- [x] Send CID to IE contract
- [ ] Await round rewards
- [ ] Clean up aggregates
```
